/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evet.managment.system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Dewanganii
 */
public class EventDetails extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public EventDetails() {
        initComponents();
    }

    public void Clearall() {

        txtEid.setText("");
        txtEname.setText("");
        jDateEstart.setCalendar(null);
        jDateEend.setCalendar(null);
        txtEvenue.setText("");
        txtDescription.setText("");

    }

    public void Insert() {

        try {
            //show confirm msg box
            int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to save this Record ? ");

            if (x == 0) {

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
                String jDateEstar = sdf.format(jDateEstart.getDate());
                String jDateEen = sdf.format(jDateEend.getDate());

                Connection c = DB.mycon();
                Statement s = c.createStatement();
                s.executeUpdate("INSERT INTO event_details (eventid,eventname,startdate,enddate,venue,description) values('" + txtEid.getText() + "','" + txtEname.getText() + "','" + jDateEstar + "','" + jDateEen + "','" + txtEvenue.getText() + "','" + txtDescription.getText() + "')");
                JOptionPane.showMessageDialog(rootPane, "record has been saved successfully");

                Clearall();

            } else if (x == 1) {
                Clearall();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void Update() {

        try {

            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
            String UpStartD = sdf.format(jDateEstart.getDate());
            String UpEndD = sdf.format(jDateEend.getDate());

            //show confirm msg box
            int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to Update this Record ? ");

            if (x == 0) {

                Connection c = DB.mycon();
                Statement s = c.createStatement();
                s.executeUpdate("UPDATE event_details SET eventname = '" + txtEname.getText() + "',startdate = '" + UpStartD + "',enddate = '" + UpEndD + "',venue = '" + txtEvenue.getText() + "',description = '" + txtDescription.getText() + "'where eventid = '" + txtEid.getText() + "' ");
                JOptionPane.showMessageDialog(rootPane, "record has been Updated successfully ");

                Clearall();

            } else if (x == 1) {
                Clearall();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void Search() {
        try {

            Connection c = DB.mycon();
            Statement s = c.createStatement();
            ResultSet rs = s.executeQuery("SELECT * FROM event_details WHERE eventid='" + txtEid.getText() + "'");

            SimpleDateFormat Esdate = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat Eedate = new SimpleDateFormat("yyyy-MM-dd");

            while (rs.next()) {
                txtEname.setText(rs.getString("eventname"));
                jDateEstart.setDate(Esdate.parse(rs.getString("startdate")));
                jDateEend.setDate(Eedate.parse(rs.getString("enddate")));
                txtEvenue.setText(rs.getString("venue"));
                txtDescription.setText(rs.getString("description"));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void Delete() {

        try {

            //show confirm msg box
            int x = JOptionPane.showConfirmDialog(rootPane, "Do you want to Delete this Record ? ");

            if (x == 0) {

                Connection c = DB.mycon();
                Statement s = c.createStatement();
                s.executeUpdate("DELETE FROM event_details WHERE eventid='" + txtEid.getText() + "'");
                JOptionPane.showMessageDialog(rootPane, "record has been not Deleted successfully ");
                
                Clearall();

            } else if (x == 1) {
                Clearall();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label2 = new java.awt.Label();
        txtEname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateEstart = new com.toedter.calendar.JDateChooser();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnHome = new javax.swing.JToggleButton();
        txtEvenue = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        txtEid = new javax.swing.JTextField();
        label5 = new java.awt.Label();
        jDateEend = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setText("Event Details");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 40, 300, 48);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sandu\\Documents\\NetBeansProjects\\Event_Management_System\\src\\images\\blu.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1370, 120);

        label2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        label2.setText("Event Name");
        getContentPane().add(label2);
        label2.setBounds(140, 200, 160, 30);
        getContentPane().add(txtEname);
        txtEname.setBounds(320, 200, 200, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sandu\\Documents\\NetBeansProjects\\Event_Management_System\\src\\images\\doc_645f9c0a5b7fab6d0c177f8df29e64cd.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(780, 510, 550, 250);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sandu\\Documents\\NetBeansProjects\\Event_Management_System\\src\\images\\BGL_123_party-champagne2014.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(750, 260, 540, 310);
        getContentPane().add(jDateEstart);
        jDateEstart.setBounds(320, 250, 200, 20);

        label3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        label3.setText("Start Date");
        getContentPane().add(label3);
        label3.setBounds(140, 250, 160, 30);

        label4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        label4.setText("Venue");
        getContentPane().add(label4);
        label4.setBounds(140, 330, 140, 32);

        btnDelete.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(330, 500, 110, 40);

        btnUpdate.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(210, 500, 100, 40);

        btnInsert.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(90, 500, 100, 40);

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Event Name", "Event Date", "venue"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(80, 580, 570, 90);

        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setText("Go to the Home page");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome);
        btnHome.setBounds(470, 500, 190, 40);
        getContentPane().add(txtEvenue);
        txtEvenue.setBounds(320, 330, 200, 20);

        label1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        label1.setText("Event ID");
        getContentPane().add(label1);
        label1.setBounds(140, 150, 140, 25);

        txtEid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEidKeyReleased(evt);
            }
        });
        getContentPane().add(txtEid);
        txtEid.setBounds(320, 150, 200, 20);

        label5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        label5.setText("End Date");
        getContentPane().add(label5);
        label5.setBounds(140, 290, 130, 32);
        getContentPane().add(jDateEend);
        jDateEend.setBounds(320, 290, 200, 20);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setText("Discription");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 380, 110, 21);

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane2.setViewportView(txtDescription);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(320, 370, 200, 96);

        setSize(new java.awt.Dimension(1384, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed

        Insert();

    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed

        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Delete();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtEidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEidKeyReleased

        Search();
    }//GEN-LAST:event_txtEidKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JToggleButton btnHome;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private com.toedter.calendar.JDateChooser jDateEend;
    private com.toedter.calendar.JDateChooser jDateEstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEid;
    private javax.swing.JTextField txtEname;
    private javax.swing.JTextField txtEvenue;
    // End of variables declaration//GEN-END:variables
}
